### ISSUE TITLE
Provider crashes when creating a Subnet with an unknown block

### ISSUE THREAD

**Issue by tsenay** [EfficientIP-Labs/terraform-provider-solidserver#3]
This issue is non blocking but provider should not crash

Step to reproduce
The offending value is `block`

### Source
```
terraform {
  required_version = "= 1.0.8"
  required_providers {
    solidserver = {
      source = "EfficientIP-Labs/solidserver"
      version = "1.1.15"
    }
  }
}

resource "solidserver_ip_subnet" "vpc" {
  space       = local.ddi_space
  name        = "name"
  block       = "BAD VALUE" 
  prefix_size = tonumber(var.vpc_cidr_block_size)
  terminal    = false
  class       = "CLASS"
  class_parameters = {
    aws_project_name        = var.project_name
    aws_project_environment = var.env_name
  }
}
```

### Stack trace

```
Stack trace from the terraform-provider-solidserver_v1.1.15 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 98 [running]:
github.com/EfficientIP-Labs/terraform-provider-solidserver/solidserver.resourceipsubnetCreate(0xc00018c770, 0x1b40340, 0xc0004660e0, 0x2, 0x2674d40)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/solidserver/resource_ip_subnet.go:188 +0x2612
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00052ca00, 0xc000176ff0, 0xc000276700, 0x1b40340, 0xc0004660e0, 0x1b2f001, 0xc0003e3358, 0xc00008b560)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00052d700, 0xc00021d8e0, 0xc000176ff0, 0xc000276700, 0xc000496748, 0xc000506120, 0x1b30c40)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0005060f0, 0x1ef6d40, 0xc00008a570, 0xc0006442a0, 0xc0005060f0, 0xc00008a570, 0xc00033ca48)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8b4
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1c37b00, 0xc0005060f0, 0x1ef6d40, 0xc00008a570, 0xc000644240, 0x0, 0x1ef6d40, 0xc00008a570, 0xc000462280, 0x250)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001422c0, 0x1f03900, 0xc000590900, 0xc00008e100, 0xc000409560, 0x263b020, 0x0, 0x0, 0x0)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/google.golang.org/grpc/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc0001422c0, 0x1f03900, 0xc000590900, 0xc00008e100, 0x0)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/google.golang.org/grpc/server.go:1275 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000508430, 0xc0001422c0, 0x1f03900, 0xc000590900, 0xc00008e100)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/google.golang.org/grpc/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/google.golang.org/grpc/server.go:708 +0xa1

Error: The terraform-provider-solidserver_v1.1.15 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by alexissavin** [comment]
Should be fixed in release v1.1.16
