### ISSUE TITLE
Crash importing subnet

### ISSUE THREAD

**Issue by slargo** [EfficientIP-Labs/terraform-provider-solidserver#6]
Hi, 

We have been using IPAM for years, so all of our network is already created. We're getting a crash, when we try to import a existent subnet. 

We have this resource in the main.tf 
```
resource "solidserver_ip_subnet" "PRE_MECCANO_BBDD_01" {
  space            = ""
  request_ip       = ""
  prefix_size      = ""
  name             = ""
  terminal         = ""
}
```
We try to import the subnet with id 64377:

```
terraform import solidserver_ip_subnet.PRE_MECCANO_BBDD_01 
64377
solidserver_ip_subnet.PRE_MECCANO_BBDD_01: Importing from ID "64377"...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more        
│ details.
╵


Stack trace from the terraform-provider-solidserver_v1.1.15 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 43 [running]:
github.com/EfficientIP-Labs/terraform-provider-solidserver/solidserver.resourceipsubnetImportState(0xc0003fa070, 0xf49040, 0xc000182bd0, 0x15, 0xc000224dc8, 0x7f36eb150701, 0x0, 0x1)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/solidserver/resource_ip_subnet.go:527 +0x14d9        
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ImportState(0xc0004da080, 0xc00067b9a0, 0xc0002743f8, 0x5, 0x95c3b4, 0xc00019ee60, 0x1e, 0x1e, 0x1012c80)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:390 +0x28b
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ImportResourceState(0xc000010af0, 0x1300ca0, 0xc000113dd0, 0xc00062c2c0, 0xc000010af0, 0xc000113dd0, 0xc000071a48)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:953 +0xec
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ImportResourceState_Handler(0x1040be0, 0xc000010af0, 0x1300ca0, 0xc000113dd0, 0xc00007e4e0, 0x0, 0x1300ca0, 0xc000113dd0, 0xc00019ee60, 0x1e)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3207 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000342c0, 0x130d600, 0xc0006c2a80, 0xc0000ca000, 0xc000612390, 0x1a48258, 0x0, 0x0, 0x0)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/google.golang.org/grpc/server.go:995 +0x460   
google.golang.org/grpc.(*Server).handleStream(0xc0000342c0, 0x130d600, 0xc0006c2a80, 0xc0000ca000, 0x0)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/google.golang.org/grpc/server.go:1275 +0xd3d  
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003fe300, 0xc0000342c0, 0x130d600, 0xc0006c2a80, 0xc0000ca000)
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/google.golang.org/grpc/server.go:710 +0xa1    
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/asavin/Repositories/Go/src/github.com/EfficientIP-Labs/terraform-provider-solidserver/vendor/google.golang.org/grpc/server.go:708 +0xa1    

Error: The terraform-provider-solidserver_v1.1.15 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by alexissavin** [comment]
Should be fixed in release v1.1.16
